lannguage: php

php:
    - 5.5

before_install:
    - sudo chmod 0777 -R app/logs/ app/cache/

install:
    - composer install -n --prefer-source

before_script:
    - app/console doctrine:database:create -e test

